### ISSUE TITLE
[TASK] Main page for selling items

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/marketplace-app#1]
# Task description
When a user goes to the main page (http://let.no) the user should be shown a grid view of items for sale. 

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [ ] Create a new page for listing items that are for sale
- [ ] Items should be retrieved from backend
- [ ] Items should be shown in a grid view
- [ ] The item list should be scrollable
- [ ] Each item should display a thumbnail, a title, a brief description, a price, and a seller's name.
