### ISSUE TITLE
[TASK] Create view for changing user details and credentials

### ISSUE THREAD

**Issue by aaarunan** [BeatsuDev/marketplace-app#10]
# Task description
Users can edit their information and credentials.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] Create a form for sending new user information and credentials
- [x] Edits must be updated in backend
- [x] Show error message if an error occurs

## Task dependencies
This task requires these tasks to be completed:
- #7 
- #6
