### ISSUE TITLE
[TASK] Bookmark a listing

### ISSUE THREAD

**Issue by ericbstie** [BeatsuDev/marketplace-app#13]
# Task description
A user should be able to bookmark a listing by clicking a bookmark button or icon. 

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] Add a bookmark button / icon
- [x] Update bookmarks for the user in backend
- [x] Show any eventual errors

## Task dependencies
This task requires these tasks to be completed:
- #8
