### ISSUE TITLE
[TASK] "Create Listing" page

### ISSUE THREAD

**Issue by ericbstie** [BeatsuDev/marketplace-app#16]
# Task description
A user should have a page for creating a new item listing.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] A new page for creating new item listings
- [x] An input field for the item listing title
- [x] An input field for a brief description
- [x] An input field for a description
- [x] An input field for price
- [x] An input field for place
- [x] A way to upload images 
- [x] A submit button that creates the listing through the backend REST API
- [x] Must show an error message if something goes wrong

## Task dependencies
This task requires these tasks to be completed:
None
