### ISSUE TITLE
[TASK] Create a list of categories with subcategories

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/marketplace-app#3]
# Task description
A category should have subcategories to narrow the search field of items for sale. For example, an "Electronics" category should be able to have the "Computers" and "Mobile phones" subcategories. These subcategories could have more subcategories such as "Gaming computers" and "Work computers". 

Categories should be shown on the main page together with the items for sale, just as in task #2. The lowest level subcategories should have checkable boxes, which when checked, filter the item list to only show items from the checked categories. Multiple categories can be checked, which then shows items from all the checked categories.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [ ] A category with subcategories must be collapsable when clicked on. E.g. When Electronics is clicked, the options Computers and Mobile phones should show up under it. 
- [ ] Subcategories must be clearly differentiated from their parent category.
- [ ] Only the lowest level categories should have a checkbox.
- [ ] Checking multiple subcategories should show items that fit any of those subcategories.

## Task dependencies
This task requires these tasks to be completed:
 - #2
