### ISSUE TITLE
[TASK] REST API for retrieving items given filters

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/marketplace-app#5]
# Task description
Items for sale should be stored in a database and retrievable through a REST API at the endpoint /item. One should also be able to filter items given the parameters:
 - Search string
 - Position + radius
 - Seller
 - Whether or not the times are favorited by you
 - Categories of the item
 - The state of the item (sold, archived, active...)

The API must support pagination. 

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [ ] A REST API endpoint for retrieving all items for sale
- [ ] Filterable by search string
- [ ] Filterable by location
- [ ] Filterable by seller
- [ ] Filterable by favorited
- [ ] Filterable by categories
- [ ] Filteraby the state of the item
- [ ] Pagination

## Task dependencies
This task requires these tasks to be completed:
None
