### ISSUE TITLE
[TASK] Create login page

### ISSUE THREAD

**Issue by aaarunan** [BeatsuDev/marketplace-app#6]
# Task description
Allow the user to log in to the application

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] Create a form with an e-mail and password field
- [x] Validate input
- [x] Send login request to frontend
- [x] Set authenticated user and  token / cookie
- [x] Show errors if any
- [x] Redirect the user to home page

## Task dependencies
This task requires these tasks to be complete:
None
