### ISSUE TITLE
[TASK] Create registration page

### ISSUE THREAD

**Issue by aaarunan** [BeatsuDev/marketplace-app#7]
# Task description
Allow someone to register themselves as a user.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] Create a registration form with first name, last name, e-mail, and password.
- [x] Validate input
- [x] Show errors if any
- [x] Redirect the user to the home page.
- [x] Save authenticated user and token/cookie.

## Task dependencies
This task requires these tasks to be completed:
None
