### ISSUE TITLE
[TASK] Create a chat page

### ISSUE THREAD

**Issue by aaarunan** [BeatsuDev/marketplace-app#9]
# Task description
Once a user has created a chat with a seller, the user will be redirected to a chat page. On the chat page, a user can send and receive messages. When this task has been completed, look into #15 immediately.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] View the title of the listing and who the user is chatting with
- [x] An input field and a submit/send button to send messages
- [x] A container with previously sent messages between the user and the seller
- [x] In the item listing details page, create a button/icon to contact the seller of the item listing
- [x] The button should create a new chat with the buyer through the backend REST API
- [x] The button should redirect the user to the chat page with the new chat open

## Task dependencies
This task requires these tasks to be completed:
- #8
